### ISSUE TITLE
Broken on new update. 新更新时损坏

### ISSUE THREAD

**Issue by NinomaeTakonis** [2837164889/GunfireReborn-QHmod#1]
I tried this on the new update but it does not work. Many errors.

我在新的更新上尝试了这个，但它不起作用。很多错误。

![Untitled](https://github.com/2837164889/GunfireReborn-QHmod/assets/127072965/960607f9-a0c4-4644-bb2e-c503e7996ad3)

**Comment by 2837164889** [comment]
Please provide specific code

**Comment by 2837164889** [comment]
Please do not use the v0.6.1 Open Beta melon loader, use the v0.5.7 Open Beta melon loader instead

**Comment by 2837164889** [comment]
Please do not use the v0.6.1 Open Beta melonloader, use the v0.5.7 Open Beta melonloader instead
请不要使用v0.6.1 Open-Beta 甜瓜加载器,使用v0.5.7 Open-Beta甜瓜加载器即可
